apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: pytools-web
    language: python
    tier: frontend
  name: pytools
  namespace: pytools
spec:
  containers:
  - image: cjmendoza/pytools
    name: pytools
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
